### ISSUE TITLE
rebuild for EL 7.8

### ISSUE THREAD

**Issue by carlwgeorge** [iuscommunity-pkg/php72u-pecl-imagick#1]
RHEL 7.8 updates the ImageMagick package from 6.7.8.9-18 to 6.9.10.68-3.  This involves a library soname increase.  The current php72u-pecl-imagick-3.4.3-1 package won't install on RHEL 7.8.  It must be rebuilt to link against the newer library soname.

[php73-pecl-imagick is also affected](https://github.com/iusrepo/php73-pecl-imagick/issues/1).

**Comment by carlwgeorge** [comment]
This has been resolved in php72u-pecl-imagick-3.4.4-1, which is currently available from the ius-testing repo.

```
yum --enablerepo ius-testing update php72u-pecl-imagick
```

I plan to leave it there until the CentOS rebuild of 7.8 is released.

**Comment by StackKorora** [comment]
Just discovered this issue as Scientific Linux 7.8 just dropped today. Happy to report that the package in testing works well for me so far!
Thank you!

**Comment by carlwgeorge** [comment]
CentOS 7.8 has been released, and thus this has been promoted to the main repository.
